# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'design.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(281, 311)
        Form.setMinimumSize(QtCore.QSize(281, 0))
        Form.setMaximumSize(QtCore.QSize(281, 311))
        Form.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(38, 162, 105);")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        self.verticalLayout.addItem(spacerItem)
        self.order_id_edit = QtWidgets.QLineEdit(Form)
        self.order_id_edit.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.order_id_edit.setObjectName("order_id_edit")
        self.verticalLayout.addWidget(self.order_id_edit)
        self.info_label = QtWidgets.QLabel(Form)
        self.info_label.setText("")
        self.info_label.setObjectName("info_label")
        self.verticalLayout.addWidget(self.info_label)
        self.close_order_btn = QtWidgets.QPushButton(Form)
        self.close_order_btn.setEnabled(False)
        self.close_order_btn.setObjectName("close_order_btn")
        self.verticalLayout.addWidget(self.close_order_btn)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.verticalLayout_2.addLayout(self.verticalLayout)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Закрыть заказ"))
        self.order_id_edit.setPlaceholderText(_translate("Form", "Введите номер заказа"))
        self.close_order_btn.setText(_translate("Form", "Закрыть заказ"))
