# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'design/createOrder.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(404, 419)
        Form.setMinimumSize(QtCore.QSize(293, 363))
        Form.setMaximumSize(QtCore.QSize(404, 419))
        Form.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(38, 162, 105);")
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        self.verticalLayout.addItem(spacerItem)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(Form)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.order_id_edit = QtWidgets.QLineEdit(Form)
        self.order_id_edit.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.order_id_edit.setObjectName("order_id_edit")
        self.horizontalLayout.addWidget(self.order_id_edit)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.hours_count_box = QtWidgets.QSpinBox(Form)
        self.hours_count_box.setMinimum(1)
        self.hours_count_box.setMaximum(1000)
        self.hours_count_box.setObjectName("hours_count_box")
        self.horizontalLayout_2.addWidget(self.hours_count_box)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        self.client_box = QtWidgets.QComboBox(Form)
        self.client_box.setObjectName("client_box")
        self.horizontalLayout_3.addWidget(self.client_box)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.info_label = QtWidgets.QLabel(Form)
        self.info_label.setStyleSheet("color: rgb(224, 27, 36);")
        self.info_label.setText("")
        self.info_label.setAlignment(QtCore.Qt.AlignCenter)
        self.info_label.setObjectName("info_label")
        self.verticalLayout.addWidget(self.info_label)
        self.add_goods = QtWidgets.QPushButton(Form)
        self.add_goods.setObjectName("add_goods")
        self.verticalLayout.addWidget(self.add_goods)
        self.goods_label = QtWidgets.QLabel(Form)
        self.goods_label.setText("")
        self.goods_label.setObjectName("goods_label")
        self.verticalLayout.addWidget(self.goods_label)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.create_order_btn = QtWidgets.QPushButton(Form)
        self.create_order_btn.setObjectName("create_order_btn")
        self.verticalLayout.addWidget(self.create_order_btn)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Новый заказ"))
        self.label.setText(_translate("Form", "Номер заказа"))
        self.label_2.setText(_translate("Form", "Время проката"))
        self.hours_count_box.setSuffix(_translate("Form", " час"))
        self.label_3.setText(_translate("Form", "Клиент"))
        self.add_goods.setText(_translate("Form", "Добавить товаров"))
        self.create_order_btn.setText(_translate("Form", "Сформировать заказ"))
        self.create_order_btn.setShortcut(_translate("Form", "Return"))
